import «ProofNetLean4».Artin
import «ProofNetLean4».Axler
import «ProofNetLean4».«Cambridge-Tripos»
import «ProofNetLean4».«Dummit-Foote»
import «ProofNetLean4».Herstein
import «ProofNetLean4».«Ireland-Rosen»
import «ProofNetLean4».Munkers
import «ProofNetLean4».Pough
import «ProofNetLean4».Putnam
import «ProofNetLean4».Rudin
import «ProofNetLean4».Shakarachi
